Deeps.BookStore/Deeps.BookStore/Components/TopBooksViewComponent.cs
using Deeps.BookStore.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Deeps.BookStore.Components
{
    public class TopBooksViewComponent:ViewComponent
    {
        private readonly IBookRepository _bookRepository;

        public TopBooksViewComponent(IBookRepository bookRepository)
        {
            _bookRepository = bookRepository;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data =await _bookRepository.GetTop2Books();
            return View(data);
        }
    }
}

Deeps.BookStore/Deeps.BookStore/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Dynamic;
using Deeps.BookStore.Models;

namespace Deeps.BookStore.Controllers
{
    public class HomeController:Controller
    {
        [ViewData]
        public string Property { get; set; }
       [ViewData]
        public string Title { get; set; }
        [ViewData]
        public BookModel Book { get; set; }
        public ViewResult Index()
        {
            ViewBag.name = "deeps vewbag";
            Property = "Custom Property";
            Title = "Title from Index AM";

            dynamic data = new ExpandoObject();
            data.id = 3;
            data.name = "deeps";
            ViewBag.data = data;

            ViewBag.Type = new BookModel() { Id = 11, Title = "Pradeep Kumar" };
            Book = new BookModel() { Id = 33333, Author = "Adventure" };
            return View();
                
        }
        public ViewResult AboutUs()
        {
            ViewData["name"] = "Pradeep";
            ViewData["id"] = 333;
            ViewData["book"] = new BookModel() { Id = 3, Title = "Prasanth" };
            
            ViewBag.Title = "Title(viebag->viewdata)";
            Title = "Title from AboutUs AM";
            return View();

        }
        [Route("contact-us/{name?}", Name ="cus")]
        public ViewResult ContactUs(int id)
        {
           Title = "Title from ContactUs AM";
            if (id>0)
            {
                ViewBag.id = id;
            }
            else
            {
                ViewBag.id = null;
            }
            
            return View();          

        }
    }
}

Deeps.BookStore/Deeps.BookStore/Views/Home/AboutUs.cshtml
@{ 
    var book = ViewData["book"] as BookModel;
    //ViewData["Title"] = "AboutUs";
}

    <h1>This is a AboutUs Page</h1>
    <h2>@ViewData["name"]</h2>
    <h2>@ViewData["id"]</h2>
    <h2>@book.Id   @book.Title</h2>


@section BreadCrum{
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">About Us</a></li>
            </ol>
        </nav>        
    </div>

}

Deeps.BookStore/Deeps.BookStore/Views/Home/ContactUs.cshtml
@{
    //Layout = "_Layout";
    ViewData["Title"] = "ContactUs";
}
<div class="container">
    <h1> This is a Contact Us Page</h1>
    <h3>@ViewBag.id</h3>
    <h3>@ViewBag.name</h3>
</div>

@section BreadCrum{
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Contact Us</a></li>
            </ol>
        </nav>
    </div>

}

Deeps.BookStore/Deeps.BookStore/Views/Home/Index.cshtml
@{ 
    dynamic data = ViewBag.data;
    dynamic result = ViewBag.Type;
    //ViewData["Title"]="Home";
    var book = ViewData["book"] as BookModel;
}
@inject Deeps.BookStore.Repository.IBookRepository _bookRepository;

<section class="jumbotron text-center">
    <div class="container">
        <h3>Hello Welcome to BookStore App. I am @ViewBag.name </h3>
        <h2>Book Name</h2>
        @foreach (var item in await _bookRepository.GetAllBooks())
        {
             <h3>@item.Title</h3>
        };
        
        <p>
            @data.name   @data.id
        </p>
        <p> @result.Id @result.Title</p>
        <h3>@ViewData["property"]</h3>
        <h2>ID = @book.Id</h2>
        <h2>Author = @book.Author</h2>

        @*<div class="mt-3 p-1 bg-primary text-white rounded ">
                @DateTime.Now.ToString("dd-mm-yy")
                @{
                    int a = 3;
                    int b = 5;
                    int c = a + b;
                }
                <h1>Sum = @c</h1>
                <h1>Multiplication =@(a*b)</h1>
                <h3>My Email is deeps.dpk@gmail.com</h3>
                @{
                    var list = new List<int>() { 1, 2, 3, 4, 5, 6 };
                }
                @foreach (var x in list)
                {
                    <h3>@x</h3>
                }
                @for (int i = 0; i < 5; i++)
                {
                    <h4>
                        Hello World
                    </h4>
                }
                <img src="~/MyStaticFiles\Booklogo(1).jpg" alt="No Image" width="33" height="33" />
                <img src="~/MyStaticFiles\Book logo (3).jpg" alt="No Image" width="33" height="33" />
            </div>*@
    </div>
</section>
   
    <div class="container">
        <h3>Top Books</h3>
        @await Component.InvokeAsync("TopBooks")
        
        @*<vc:top-books></vc:top-books>*@
        
        
        @*<div class="row">
            <div class="col-md-4">
                <partial name="_bookthumbnail" model="@new BookModel()"/>
            </div>
            <div class="col-md-4">
                <partial name="_bookthumbnail" model="@new BookModel()" />
            </div>
            <div class="col-md-4">
                <partial name="_bookthumbnail" model="@new BookModel()" />
            </div>

        </div>*@
    </div>

@section scripts{
    @*<script>
            $(document).ready(function(){
                alert("The Document is Loaded Successfully");
            })
        </script>*@
}
@section BreadCrum{
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="#">Home</a></li>
                <li class="breadcrumb-item"><a href="#">Index</a></li>
            </ol>
        </nav>
    </div>

}